apiVersion: karadoc.lucca.tech/v1
kind: Component
metadata:
  name: cordova-plugin-openwith
  displayName: cordova-plugin-openwith
spec:
  owner: group:expenses
  system: system:r-d
  type: Backend
  repository: LuccaSA/cordova-plugin-openwith
